from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

from .brand_scaffold import slugify
from .runtime_support import dedupe_keep_order

GENERATED_MARKER = "<!-- generated by brand-gen prompt pack v1 -->"


def _string_list(values: Any, *, limit: int = 8) -> list[str]:
    out: list[str] = []
    if isinstance(values, list):
        raw_values = values
    elif values in (None, ""):
        raw_values = []
    else:
        raw_values = [values]
    for item in raw_values:
        text = str(item or "").strip()
        if text:
            out.append(text)
    return dedupe_keep_order(out)[:limit]


def _approved_copy(profile: dict[str, Any], identity: dict[str, Any]) -> list[str]:
    items: list[str] = []
    for source in (profile, identity):
        messaging = source.get("messaging") if isinstance(source, dict) else {}
        if not isinstance(messaging, dict):
            continue
        for key in ("tagline", "elevator"):
            value = str(messaging.get(key) or "").strip()
            if value:
                items.append(value)
        items.extend(_string_list(messaging.get("value_propositions"), limit=8))
        bank = messaging.get("approved_copy_bank") or {}
        if isinstance(bank, dict):
            for key in ("headlines", "slogans", "subheadlines"):
                items.extend(_string_list(bank.get(key), limit=8))
            for pair in bank.get("cta_pairs") or []:
                if isinstance(pair, dict):
                    items.extend(_string_list([pair.get("label"), pair.get("text")], limit=4))
                else:
                    items.append(str(pair).strip())
    return dedupe_keep_order([item for item in items if item])[:10]


def _truth_seeds(profile: dict[str, Any], identity: dict[str, Any]) -> list[str]:
    seeds: list[str] = []
    for source in (profile, identity):
        if not isinstance(source, dict):
            continue
        for key in ("description", "brand_guardrail_prelude"):
            value = str(source.get(key) or "").strip()
            if value:
                seeds.append(value)
        identity_block = source.get("identity") or {}
        if isinstance(identity_block, dict):
            seeds.extend(_string_list(identity_block.get("brand_anchors"), limit=8))
            summary = str(identity_block.get("summary") or "").strip()
            if summary:
                seeds.append(summary)
        seeds.extend(_string_list(source.get("keywords"), limit=8))
        seeds.extend(_string_list(source.get("product_categories"), limit=6))
    return dedupe_keep_order(seeds)[:12]


def _bullet_lines(items: list[str], *, fallback: str) -> str:
    values = items or [fallback]
    return "\n".join(f"- {item}" for item in values)


def render_pi_full_pipeline_prompt(
    *,
    brand_key: str,
    profile: dict[str, Any],
    identity: dict[str, Any] | None = None,
) -> str:
    identity = identity or {}
    brand_name = str(profile.get("brand_name") or identity.get("brand_name") or brand_key or "Working Brand").strip()
    resolved_key = slugify(brand_key or brand_name)
    truth = _truth_seeds(profile, identity)
    description = str(profile.get("description") or (truth[0] if truth else "")).strip()
    copy = _approved_copy(profile, identity)
    keywords = _string_list(profile.get("keywords"), limit=10)
    creative_context = profile.get("creative_context") or {}
    concept_categories = _string_list(creative_context.get("concept_categories"), limit=8) if isinstance(creative_context, dict) else []
    metaphors = _string_list(creative_context.get("metaphor_vocabulary"), limit=8) if isinstance(creative_context, dict) else []
    query_terms = dedupe_keep_order(keywords + concept_categories + [brand_name])[:8]
    query = " ".join(query_terms).strip() or brand_name

    return f"""{GENERATED_MARKER}
# Pi prompt: {brand_name} brand-gen full pipeline

Paste this into Pi from the brand-gen repository root when you want Pi to run the full brand material pipeline for **{brand_name}**.

```text
You are running brand-gen for the {brand_name} brand from the brand-gen repository root.

Use the Pi brand-gen typed-tool runtime only. Do not run shell commands and do not edit JSON/markdown memory files directly. Prefer `/run brand-orchestrator` and the `.pi/agents/brand-*.md` contracts. If you need details, read these repo-local docs first:
- docs/architecture/runtime-agent-contract.md
- docs/architecture/source-knowledge.md
- docs/architecture/gepa-dspy-optimization.md
- docs/architecture/tool-groups/orchestration.md
- docs/architecture/tool-groups/mutation.md
- docs/architecture/tool-groups/inspection-policy.md

Goal: create or iterate a {brand_name} brand material with the complete quality-gated pipeline and GEPA/DSPy-ready feedback capture.

Use this sequence:
0. Schema discipline: use only canonical typed `brand_*` tools and pass only schema-supported arguments. Put extra creative detail into accepted free-text fields (`task`, `brief`, `prompt`, `user_request`, or equivalent) or into the `/run brand-orchestrator` instruction.
1. Preflight: call `brand_context_snapshot`, `brand_source_knowledge`, `brand_list_brands`, `brand_capabilities`, `brand_show_blackboard`, `brand_show_iteration_memory`, and `brand_scoring_status`. Confirm the active brand/session is `{resolved_key}` / {brand_name}; if not, use `brand_switch_brand` for `{resolved_key}`. If `source_knowledge` is configured, query `brand_source_knowledge` with `{query}` and convert concrete source facts into prompt seeds or scratchpad notes before planning. Do not use another brand's vault as truth for {brand_name}.
2. Pipeline: run `/run brand-orchestrator "Create/iterate the requested {brand_name} brand material using prepare → plan → validate → execute → review → evolve. Use typed brand_* tools only. Stop on blocking findings or needs_user_input."`
3. Planning: use `brand_orchestrate_material` for the normal path, or `brand_prepare_run`, `brand_plan_run`, and `brand_validate_run` for stage-level fall-through. If no surface/material type is implied, ask one concise question. For exact visible copy, require deterministic HTML/SVG/composite/text overlay rendering.
4. Generation: use `brand_build_generation_scratchpad` / `brand_execute_run` with explicit cinematographer fields when supported: `generation_mode`, `aspect_ratio`, `resolution`, `duration`, `source_version`, `reference_assets`, `motion_reference`, `base_image`, and `negative_prompt`. Do not bypass blocking findings (`allow_blocking`) unless the user explicitly authorizes it.
5. Review: use the v2/DSPy scorer path when available. Always pass the required `version_id`/`version` from the previous tool's `next_action`. `disqualifier_triggered == true` rejects; otherwise `overall_score < 3` iterates; otherwise approve. `decision: pending` or empty `axis_scores` means the artifact is not reviewed.
6. GEPA/DSPy trace quality: preserve `axis_scores`, `axis_rationales`, `disqualifier_triggered`, `disqualifier_rule`, `why_user_might_dislike_if_polished`, and `before_after_diffs` in disagreement records.
7. Iteration: convert useful `before_after_diffs` rows into typed mutations. Use `brand_append_forbidden_pattern` for recurring `before` failures and `brand_append_custom_scratchpad_note` for `after` directives. Then rerun from the prior `source_version`.
8. Evolve: call `brand_evolve_run` only after an approved review or a submitted meaningful rejection. Do not evolve from a pending review packet.
9. Final response: report version id, artifact paths, score/decision, disqualifier status, top axis scores, and exact before/after diffs or durable mutations applied.
```

## {brand_name}-specific grounding

Description: {description or 'No description recorded yet. Ask one concise brand-grounding question before generation.'}

Product truth / source seeds:
{_bullet_lines(truth, fallback='Ask for concrete product truth or configure brand-scoped source knowledge before high-stakes generation.')}

Approved copy candidates:
{_bullet_lines(copy, fallback='No approved copy recorded yet. Use deterministic rendering only after approved copy is provided.')}

Creative vocabulary:
{_bullet_lines(dedupe_keep_order(keywords + concept_categories + metaphors)[:12], fallback='No creative vocabulary recorded yet.')}

## Generic guardrails

- Use source knowledge as brand-specific truth, not universal style guidance.
- Borrow inspiration as mechanics only: hierarchy, pacing, composition, materiality.
- Avoid generic AI slop: floating orbs, robot brains, fake dashboards, unreadable pseudo-text, and abstract diagrams with no artifact proof.
- If exact visible copy is required, use deterministic rendering. Do not ask an image model to invent readable text.
"""


def ensure_brand_prompt_pack(brand_dir: Path, *, profile: dict[str, Any], identity: dict[str, Any] | None = None, force: bool = False) -> dict[str, str]:
    brand_dir = Path(brand_dir).expanduser().resolve()
    brand_key = brand_dir.name
    prompts_dir = brand_dir / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)
    prompt_path = prompts_dir / "pi-full-pipeline.md"
    should_write = force or not prompt_path.exists()
    if prompt_path.exists() and not force:
        try:
            should_write = GENERATED_MARKER in prompt_path.read_text(errors="ignore")
        except OSError:
            should_write = False
    if should_write:
        prompt_path.write_text(render_pi_full_pipeline_prompt(brand_key=brand_key, profile=profile, identity=identity or {}))
    manifest = {
        "schema_type": "brand_prompt_pack",
        "schema_version": 1,
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "brand_key": brand_key,
        "prompts": {"pi_full_pipeline": str(prompt_path)},
    }
    manifest_path = prompts_dir / "prompt-pack.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    return {"prompt_path": str(prompt_path), "manifest_path": str(manifest_path)}


__all__ = ["ensure_brand_prompt_pack", "render_pi_full_pipeline_prompt"]
